packaging_format = 2

id = "phpinfo"
name = "Phpinfo"
description.en = "Simple phpinfo"
description.fr = "Simple phpinfo"

version = "1.0~ynh4"

maintainers = ["Maniack Crudelis"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.php.net/manual/fr/function.phpinfo.php"

[integration]
yunohost = ">= 11.1.16"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpinfo"

    [install.phpversion]
    ask.en = "Choose the version of PHP to use."
    ask.fr = "Choisissez la version de PHP à utiliser."
    type = "string"
    choices = ["7.4", "8.0", "8.1", "8.2"]
    default = "8.0"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-fpm"