test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private", "change_url"]
    
    # -------------------------------
    # Default args to use for install
    # -------------------------------
