test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private", "change_url"]
    
    # -------------------------------
    # Default args to use for install
    # -------------------------------

    [80_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.0"

    [82_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.2"
